apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledgecity-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledgecity-backend
  template:
    metadata:
      labels:
        app: knowledgecity-backend
    spec:
      imagePullSecrets:
      - name: testfourids-auth
      containers:
      - name: azure-backend
        image: maheshbmahesh/azure-backend:latest     
        ports:
        - containerPort: 80
